### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by maxzinkus** [jack4818/kyber-py#2]
This is a really excellent repo. Creating a clear and readable version of crypto algorithms, especially (closer to) emerging ones, is such a great teaching tool. I really appreciate your work on this.

That's it, that's the issue! Thanks again 🙂

(also- M1 Max benches come in around 2x the i7! 😎)

```
(using os.urandom)
-------------------------
  Kyber512 | (1000 calls)
-------------------------
keygen:  3.71204s
encrypt: 5.63528s
decrypt: 8.88659s

-------------------------
  Kyber768 | (1000 calls)
-------------------------
keygen:  5.55999s
encrypt: 8.27046s
decrypt: 12.9365s

-------------------------
  Kyber1024 | (1000 calls)
-------------------------
keygen:  8.22987s
encrypt: 11.56816s
decrypt: 17.76398s
```

**Comment by jack4818** [comment]
Thanks Max!! I could add these benchmarks to the README when I next edit it too. Envious of your M1 Max!

Really happy that you enjoyed the code, having it as a teaching aid was my number 1 goal.
