### ISSUE TITLE
Add documentation for NTT 

### ISSUE THREAD

**Issue by Sujjan19** [jack4818/kyber-py#3]
Really good work man!, I could understand most of working of Kyber,  because of this implementation (& baby kyber ofc ).
Please add documentation for NTT helpers also.
Thanks.

**Comment by jack4818** [comment]
It's on my todo, but I keep getting distracted. I'll ping you in this issue once I have done it, but if you're interested about NTT stuff, see "Polynomial Multiplication for Post-Quantum Cryptography", https://kannwischer.eu/thesis/

**Comment by Sujjan19** [comment]
Thnx for the reference, I'll go through it, might get distracted myself but i'll try ; )
